---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - plugin.github.com.ellioben
  resources:
  - extpowers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - plugin.github.com.ellioben
  resources:
  - extpowers/finalizers
  verbs:
  - update
- apiGroups:
  - plugin.github.com.ellioben
  resources:
  - extpowers/status
  verbs:
  - get
  - patch
  - update
